### ISSUE TITLE
throttle-debounce exports issue

### ISSUE THREAD

**Issue by stephenway** [michaeldzjap/react-signature-pad-wrapper#25]
It looks as though the latest release of this package breaks our Docker build with the following error:

```shell
Error: Package exports for '/app/node_modules/throttle-debounce' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/react-signature-pad-wrapper/dist/react-signature-pad-wrapper.js:1:90)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

Rolling back to the last version of react-signature-pad-wrapper resolved this issue.

**Comment by michaeldzjap** [comment]
That unfortunately doesn't give me much to go on. I would at least need a minimal reproducible example to be able to figure out what could be causing this.

The example still seems to work fine, so I am inclined to think it rather could be something on your end. Not sure what your docker setup is, but perhaps it is worth a try deleting _node_modules_ and _package-lock.json_. Perhaps it could also be a latest _node_ version issue, hard to tell...

**Comment by stephenway** [comment]
Turns out the hint I was looking for was Node! The docker image was built using Node 13.1, but we wanted to target Node 10. Downgrading it resolved the issue. Thanks!
